apiVersion: apps/v1
kind: Deployment
metadata:
  name: student6-deployment
  namespace: student6
spec:
  selector:
    matchLabels:
      app: student6
  template:
    metadata:
      labels:
        app: student6
    spec:
      containers:
      - name: student6
        image: registry.tanzu.dk/ops2devops/student6:v1
