apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentx-deployment
  namespace: student6
spec:
  selector:
    matchLabels:
      app: student6
  template:
    metadata:
      labels:
        app: student6
    spec:
      containers:
      - name: student6
        image: registry.tanzu.dk/ops2devops/student6:master
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: student6
spec:
  type: NodePort
  selector:
    app: student6
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30016 # Remember to change to student number.

